version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - appNetwork
    dns:
      - 8.8.8.8
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - appNetwork
    dns:
      - 8.8.8.8
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: projekt_zespolowy
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - appNetwork
    volumes:
      - mysql_data:/var/lib/mysql
    dns:
      - 8.8.8.8

networks:
  appNetwork:
    driver: bridge

volumes:
  mysql_data:
    driver: local
